export const projects = [
    {
        id: "01",
        title: "JOURNEY",
        link: "https://www.therookies.co/entries/17064",
        description: "For this Project, I was planning on creating a series of cinematic renders that show the journey of two frogs. It was a project that presented a challenge in executing multiple aspects of 3D like modeling, texturing, rigging, lighting and composition. I'm quite happy with the results and I hope you'll also enjoy taking a look.", 
        video: "",
        imageOne: "/Assets/Projects/Journey/img-1.jpg",
        imageTwo: "/Assets/Projects/Journey/img-2.jpg",
        imageThree: "/Assets/Projects/Journey/img-3.jpg",
    },
    {
        id: "02",
        title: "CREATURE CONCEPT",
        link: "https://www.therookies.co/projects/38969",
        description: "This project was a practice in creating characters. For this entry, I sculpted, retopologized, and textured a creature character based on the beautiful concept art of Brent Hollowell. I took some liberty in tweaking the facial proportions to my liking. I preferred a gentler-looking face to the mean, rugged look of the concept art. The software used are blender for sculpting and retopo, Substance painter for the texturing, Blender Cycles, and Photoshop for rendering and post-processing. I hope you like the results.", 
        video: "",
        imageOne: "/Assets/Projects/Creature Concept/img-1.jpg",
        imageTwo: "/Assets/Projects/Creature Concept/img-2.jpg",
        imageThree: "/Assets/Projects/Creature Concept/img-3.jpg",
    },
    {
        id: "03",
        title: "RAPTORS",
        link: "https://www.therookies.co/projects/39199",
        description: "This entry was an attempt to create a short but cinematic animation that somehow looked like the opening shot of a full-fledged movie. Even though the final result is a 15-second clip, I'm quite happy with the results. Here are some behind-the-scenes images alongside the results. I hope you like what you see.", 
        video: "/Assets/Projects/Raptor/video.mp4",
        imageOne: "/Assets/Projects/Raptor/img-1.jpg",
        imageTwo: "/Assets/Projects/Raptor/img-2.jpg",
        imageThree: " ",
    },
    {
        id: "04",
        title: "CHAMELEON",
        link: "https://www.therookies.co/projects/38931",
        description: "For this project, I particularly focused on achieving photorealism. A challenge while creating this was adding scales with texturing because sculpting them was difficult due to my current hardware capabilities. I hope you like taking a look at the results. Thank you.", 
        video: "",
        imageOne: "/Assets/Projects/Chameleon/img-1.jpg",
        imageTwo: "/Assets/Projects/Chameleon/img-2.jpg",
        imageThree: "/Assets/Projects/Chameleon/img-3.jpg ",
    },
    {
        id: "05",
        title: "OLD HANGAR",
        link: "https://www.therookies.co/projects/38911",
        description: "This is a project I did a while ago as a practice in composition, hard surface modeling and texturing. I've also experimented with two variations in mood and lighting. I hope you'll enjoy taking a look. Thank you.", 
        video: "",
        imageOne: "/Assets/Projects/Hangar/img-1.jpg",
        imageTwo: "/Assets/Projects/Hangar/img-2.jpg",
        imageThree: "/Assets/Projects/Hangar/img-3.jpg ",
    },


]